version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    command: phpunit
    volumes:
      - ../:/usr/src/app
    environment:
<<<<<<< HEAD
      - PHP_EXTENSIONS=intl pdo_sqlite sqlite3
      - STARTUP_COMMAND_1=composer install
      - STARTUP_COMMAND_2=bash test/reset_tests.sh
=======
      - PHP_EXTENSIONS=intl pdo_sqlite sqlite3 xdebug
      - STARTUP_COMMAND_1=composer install
      - STARTUP_COMMAND_2=bash test/reset_tests.sh
      - PHP_IDE_CONFIG="serverName=propel"
      - XDEBUG_MODE=debug
      - XDEBUG_SESSION=1
>>>>>>> 73148f83 (compatibility with php 7.4 and 8.x (#4))

  db:
    image: percona
    command: >
      mysqld
      --sql-mode="NO_ENGINE_SUBSTITUTION"
      --character-set-server="utf8"
      --collation-server="utf8_unicode_ci"
      --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
